#
# Define variables of module groups for use by the sebsjames/maths
# build process itself, and by client projects.
#
macro(setup_module_variables_for_maths base_directory)

  set(SM_MATHCONST_MODULES
    ${base_directory}/sm/mathconst.cppm
  )
  set(SM_CONSTEXPR_MATH_MODULES
    ${SM_MATHCONST_MODULES}
    ${base_directory}/sm/constexpr_math.cppm
  )
  set(SM_POLYSOLVE_MODULES
    ${SM_CONSTEXPR_MATH_MODULES}
    ${base_directory}/sm/polysolve.cppm
  )
  set(SM_BESSEL_I0_MODULES
    ${SM_POLYSOLVE_MODULES}
    ${base_directory}/sm/bessel_i0.cppm
  )
  set(SM_RANDOM_MODULES
    ${SM_BESSEL_I0_MODULES}
    ${base_directory}/sm/random.cppm
  )
  set(SM_RANGE_MODULES
    ${SM_CONSTEXPR_MATH_MODULES}
    ${base_directory}/sm/trait_tests.cppm
    ${base_directory}/sm/range.cppm
  )
  set(SM_VEC_MODULES
    ${SM_RANGE_MODULES}
    ${SM_RANDOM_MODULES}
    ${base_directory}/sm/vec.cppm
  )
  set(SM_VVEC_MODULES
    ${SM_RANGE_MODULES}
    ${SM_RANDOM_MODULES}
    ${base_directory}/sm/vvec.cppm
  )
  set(SM_SCALE_MODULES
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/scale.cppm
  )
  set(SM_UTIL_MODULES
    ${base_directory}/sm/trait_tests.cppm
    ${base_directory}/sm/util.cppm
  )
  set(SM_HDFDATA_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${SM_UTIL_MODULES}
    ${base_directory}/sm/hdfdata.cppm
  )
  set(SM_QUATERNION_MODULES
    ${SM_VEC_MODULES}
    ${base_directory}/sm/quaternion.cppm
  )
  set(SM_MAT_MODULES
    ${SM_QUATERNION_MODULES}
    ${base_directory}/sm/mat.cppm
  )
  set(SM_BEZCOORD_MODULES
    ${SM_VEC_MODULES}
    ${base_directory}/sm/bezcoord.cppm
  )
  set(SM_HEX_MODULES
    ${SM_BEZCOORD_MODULES}
    ${base_directory}/sm/hex.cppm
  )
  set(SM_RECT_MODULES
    ${SM_BEZCOORD_MODULES}
    ${base_directory}/sm/rect.cppm
  )
  set(SM_WINDER_MODULES
    ${SM_VEC_MODULES}
    ${base_directory}/sm/winder.cppm
  )
  set(SM_BOOTSTRAP_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/bootstrap.cppm
  )
  set(SM_GRID_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/grid.cppm
  )
  set(SM_ALGO_MODULES
    ${SM_VEC_MODULES}
    ${base_directory}/sm/algo.cppm
  )
  set(SM_NM_SIMPLEX_MODULES
    ${SM_ALGO_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/nm_simplex.cppm
  )
  set(SM_HISTO_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/histo.cppm
  )
  set(SM_BOXFILTER_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/boxfilter.cppm
  )
  set(SM_GEOMETRY_MODULES
    ${SM_ALGO_MODULES}
    ${SM_VVEC_MODULES}
    ${base_directory}/sm/geometry.cppm
  )
  set(SM_BEZCURVE_MODULES
    ${SM_BEZCOORD_MODULES}
    ${SM_MAT_MODULES}
    ${SM_NM_SIMPLEX_MODULES}
    ${base_directory}/sm/binomial.cppm
    ${base_directory}/sm/bezcurve.cppm
  )
  set(SM_BEZCURVEPATH_MODULES
    ${SM_BEZCURVE_MODULES}
    ${base_directory}/sm/bezcurvepath.cppm
  )
  set(SM_HEXGRID_MODULES
    ${SM_BEZCURVEPATH_MODULES}
    ${SM_HEX_MODULES}
    ${base_directory}/sm/hexgrid.cppm
  )
  set(SM_CARTGRID_MODULES
    ${SM_BEZCURVEPATH_MODULES}
    ${SM_RECT_MODULES}
    ${SM_GRID_MODULES}
    ${base_directory}/sm/cartgrid.cppm
  )
  set(SM_CONFIG_MODULES
    ${SM_VEC_MODULES}
    ${SM_VVEC_MODULES}
    ${SM_UTIL_MODULES}
    ${base_directory}/sm/config.cppm
  )
  set(SM_CRC32_MODULES
    ${base_directory}/sm/crc32.cppm
  )
  set(SM_FLAGS_MODULES
    ${base_directory}/sm/flags.cppm
  )

  set(SM_ALL_MODULES
    ${base_directory}/sm/algo.cppm
    ${base_directory}/sm/anneal.cppm
    ${base_directory}/sm/base64.cppm
    ${base_directory}/sm/bessel_i0.cppm
    ${base_directory}/sm/bezcoord.cppm
    ${base_directory}/sm/bezcurve.cppm
    ${base_directory}/sm/bezcurvepath.cppm
    ${base_directory}/sm/binomial.cppm
    ${base_directory}/sm/bootstrap.cppm
    ${base_directory}/sm/boxfilter.cppm
    ${base_directory}/sm/cartgrid.cppm
    ${base_directory}/sm/centroid.cppm
    ${base_directory}/sm/CMakeLists.txt
    ${base_directory}/sm/config.cppm
    ${base_directory}/sm/constexpr_math.cppm
    ${base_directory}/sm/crc32.cppm
    ${base_directory}/sm/edgeconv.cppm
    ${base_directory}/sm/flags.cppm
    ${base_directory}/sm/geometry.cppm
    ${base_directory}/sm/geometry_polyhedra.cppm
    ${base_directory}/sm/grid.cppm
    ${base_directory}/sm/hdfdata.cppm
    ${base_directory}/sm/hex.cppm
    ${base_directory}/sm/hexgrid.cppm
    ${base_directory}/sm/hexgrid_hdf.cppm
    ${base_directory}/sm/hexyhisto.cppm
    ${base_directory}/sm/histo.cppm
    ${base_directory}/sm/mat.cppm
    ${base_directory}/sm/mathconst.cppm
    ${base_directory}/sm/maths-config.cmake
    ${base_directory}/sm/nm_simplex.cppm
    ${base_directory}/sm/onoff.cppm
    ${base_directory}/sm/polysolve.cppm
    ${base_directory}/sm/quaternion.cppm
    ${base_directory}/sm/random.cppm
    ${base_directory}/sm/range.cppm
    ${base_directory}/sm/rect.cppm
    ${base_directory}/sm/scale.cppm
    ${base_directory}/sm/trait_tests.cppm
    ${base_directory}/sm/util.cppm
    ${base_directory}/sm/vec.cppm
    ${base_directory}/sm/vvec.cppm
    ${base_directory}/sm/winder.cppm
  )

endmacro()
