name: Ubuntu gcc15 cmake + ninja
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
      - 'examples/screenshots/**'
      - 'examples/docs/**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    uses: sebsjames/maths/.github/workflows/ubuntu-cmakeninja-template.yml@main
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      COMPILER_PACKAGES: gcc-15 g++-15
      CC: gcc-15
      CXX: g++-15
