name: Ubuntu clang22 modules
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'README**'
      - 'examples/screenshots/**'
      - 'examples/docs/**'
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-passing-data:
    uses: sebsjames/maths/.github/workflows/ubuntu-modules-template.yml@main
    with:
      RUNNER_IMAGE: ubuntu-24.04
      BUILD_TYPE: Release
      COMPILER_PACKAGES: clang-20 clang-tools-20
      COMPILER_INSTALL:
        wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.2/LLVM-22.1.2-Linux-X64.tar.xz ;
        sudo mkdir -p /opt/llvm ;
        sudo tar xf LLVM-22.1.2-Linux-X64.tar.xz -C /opt/llvm
        rm LLVM-22.1.2-Linux-X64.tar.xz
      CC: /opt/llvm/LLVM-22.1.2-Linux-X64/bin/clang
      CXX: /opt/llvm/LLVM-22.1.2-Linux-X64/bin/clang++
